/**
 * @file td_lock.h
 * @author Xiahua Liu @xiahualiu
 * @brief Thread lock table class, used for lock management on a worker thread.
 * @version 0.1
 * @date 2025-01-02
 *
 * @copyright MIT License
 *
 */

#ifndef PAWNDB_THREAD_LOCK_H
#define PAWNDB_THREAD_LOCK_H

#include <sys/types.h>

#include <array>
#include <tuple>

#include "pawndb/ds/hash.h"
#include "pawndb/params.h"

namespace PawnDB {

/**
 * @brief Enumeration of possible lock table errors.
 */
enum class LockError {
  None,         /**< No error */
  LockConflict, /**< Lock conflict */
  LockNotFound, /**< Lock not found */
  LockFull,     /**< Lock table is full */
  Unknown,      /**< Unknown error */
};

/**
 * @brief Enumeration of lock types.
 */
enum class LockType {
  Shared,    /**< Shared lock */
  Exclusive, /**< Exclusive lock */
};

/**
 * @brief Lock table data structure.
 */
class LockTable {
 public:
  LockTable() = default;

  using key_t = std::uint16_t;

  /**
   * @brief Checks if the hash table is full.
   *
   * This function returns a boolean value indicating whether the hash table
   * has reached its maximum capacity.
   *
   * @return true if the hash table is full, false otherwise.
   */
  bool full() const noexcept { return hash_table.full(); }

  /**
   * @brief Checks if the hash table is empty.
   *
   * This function returns a boolean value indicating whether the hash table
   * is empty.
   *
   * @return true if the hash table is empty, false otherwise.
   */
  bool empty() const noexcept { return hash_table.empty(); }

  /**
   * @brief Locks a tuple in the table.
   *
   * @param _tbl The table ID.
   * @param _key The tuple key.
   * @param _lk The type of lock.
   * @return LockError::None if the operation is successful, otherwise an
   * appropriate LockError.
   */
  LockError lock(tp_id_t _tbl, tbl_row_t _key, LockType _lk) noexcept {
    auto hash_key = key(_tbl, _key);
    auto insert_r = hash_table.insert(hash_key);
    switch (insert_r.getError()) {
      case HashError::None:
        locks[insert_r.unwrap()] = _lk;
        return LockError::None;
      case HashError::Full: return LockError::LockFull;
      case HashError::Duplicate: return LockError::LockConflict;
      default: return LockError::Unknown;
    }
  }

  /**
   * @brief Unlocks a tuple in the table.
   *
   * @param _tbl The table ID.
   * @param _key The tuple key.
   * @return LockError::None if the operation is successful, otherwise an
   * appropriate LockError.
   */
  LockError unlock(tp_id_t _tbl, tbl_row_t _key) noexcept {
    auto hash_key = key(_tbl, _key);
    auto search_r = hash_table.remove(hash_key);
    switch (search_r.getError()) {
      case HashError::None: return LockError::None;
      case HashError::NotFound: return LockError::LockNotFound;
      default: return LockError::Unknown;
    }
  }

  /**
   * @brief Promotes a shared lock to an exclusive lock.
   *
   * @param _tbl The table ID.
   * @param _key The tuple key.
   * @return LockError::None if the operation is successful, otherwise an
   * appropriate LockError.
   */
  LockError promote(tp_id_t _tbl, tbl_row_t _key) noexcept {
    auto hash_key = key(_tbl, _key);
    auto search_r = hash_table.search(hash_key);
    if (!search_r) return LockError::LockNotFound;
    locks[search_r.unwrap()] = LockType::Exclusive;
    return LockError::None;
  }

  /**
   * @brief Generates a unique key by combining table ID and row key.
   *
   * This function takes a table ID and a row key, and combines them into a
   * single unique key. The row key is shifted left by 8 bits and then combined
   * with the table ID using a bitwise OR operation.
   *
   * @param _tbl The table ID.
   * @param _key The row key.
   * @return A unique key generated by combining the table ID and row key.
   */
  key_t key(tp_id_t _tbl, tbl_row_t _key) noexcept {
    return static_cast<key_t>(_key << 8 | _tbl);
  }

  /**
   * @brief Generates a pair consisting of a table partition ID and a table row
   * ID from a given key.
   *
   * This function takes a key and splits it into two parts:
   * - The lower 8 bits of the key represent the table ID.
   * - The remaining bits of the key represent the table row ID.
   *
   * @param _key The key to be split into a table partition ID and a table row
   * ID.
   * @return A std::pair where the first element is the table partition ID
   * (tp_id_t) and the second element is the table row ID (tbl_row_t).
   */
  std::pair<tp_id_t, tbl_row_t> key(key_t _key) const noexcept {
    return std::make_pair(_key & 0xff, _key >> 8);
  }

  using LockR = Result<LockType, LockError>;

  /**
   * @brief Gets the lock type of a tuple in the table.
   *
   * @param _tbl The table ID.
   * @param _key The tuple key.
   * @return A Result object containing the lock type if the operation is
   * successful, otherwise an appropriate LockError.
   */
  LockR get(tp_id_t _tbl, tbl_row_t _key) noexcept {
    auto hash_key = key(_tbl, _key);
    auto search_r = hash_table.search(hash_key);
    if (!search_r) return LockError::LockNotFound;
    return locks[search_r.unwrap()];
  }

  /**
   * @brief Iterator class for the lock table.
   */
  class ConstIterator {
   public:
    using iterator_category = std::forward_iterator_tag;
    using value_type = std::tuple<tp_id_t, tbl_row_t, LockType>;
    using difference_type = std::ptrdiff_t;
    using pointer = const value_type*;
    using reference = const value_type&;

    ConstIterator(const LockTable* _table, size_t _index)
        : table(_table), index(static_cast<tbl_row_t>(_index)) {
      advance_to_valid();
    }

    /**
     * @brief Dereference operator to access the value at the current iterator
     * position.
     *
     * This operator returns a tuple containing the table, key, and lock
     * associated with the current index in the hash table.
     *
     * @return A tuple consisting of:
     * - The table associated with the current hash key.
     * - The key associated with the current hash key.
     * - The lock associated with the current hash key.
     */
    value_type operator*() const {
      auto hash_key = table->hash_table[index];
      auto [tbl, key] = table->key(hash_key);
      return std::make_tuple(tbl, key, table->locks[hash_key]);
    }

    ConstIterator& operator++() {
      ++index;
      advance_to_valid();
      return *this;
    }

    ConstIterator operator++(int) {
      ConstIterator tmp = *this;
      ++(*this);
      return tmp;
    }

    friend bool operator==(const ConstIterator& a, const ConstIterator& b) {
      return a.index == b.index;
    }

    friend bool operator!=(const ConstIterator& a, const ConstIterator& b) {
      return a.index != b.index;
    }

   private:
    /**
     * @brief Advances the index to the next valid entry in the hash table.
     *
     * This function increments the index until it points to a valid entry
     * in the hash table or reaches the maximum number of locks per transaction.
     */
    void advance_to_valid() {
      while (index < MAX_LOCK_PER_TRANSACTION &&
             !table->hash_table.is_valid(index)) {
        ++index;
      }
    }

    const LockTable* table;
    tbl_row_t index;
  };

  ConstIterator begin() const { return ConstIterator(this, 0); }
  ConstIterator end() const {
    return ConstIterator(this, MAX_LOCK_PER_TRANSACTION);
  }

 private:
  Hash<key_t, MAX_LOCK_PER_TRANSACTION> hash_table;
  std::array<LockType, MAX_LOCK_PER_TRANSACTION> locks;
};

}  // namespace PawnDB

#endif  // PAWNDB_THREAD_LOCK_H
