name: Aarch64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu_latest
          install: | 
            apt-get update && apt-get install -y cmake build-essential ninja-build
          run: |
            cmake -S . -B build -DI_AM_CI_MACHINE=1 -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain/gcc.cmake
            cmake --build build --target pawndb
