name: Aarch64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - uses: uraimo/run-on-arch-action@v3
        with:
          arch: aarch64
          distro: ubuntu_latest
          install: | 
            apt-get update && apt-get install -y cmake build-essential ninja-build
          run: |
            cmake -S . -B build -G Ninja -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/gcc.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
            cmake --build build --target pawndb-app -j
