name: Doxygen

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: install required packages
        run: |
          sudo apt-get update && sudo apt-get install -y doxygen graphviz dia mscgen cmake ninja-build

      - name: build and run doxygen
        run: |
          cmake -S . -B build -G Ninja -DPAWNDB_ENABLE_DOXYGEN=ON
          cmake --build build --target doxygen 
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/docs/html
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: doxygen-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4