name: Install

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: build and install library
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          sudo cmake --build build --target install
          rm -rf build

      - name: configure
        run: cmake -S . -B build -DTEST_INSTALLED_VERSION=1

      - name: build
        run: cmake --build build --target PawnDB_Tests -j4

      - name: test
        run: |
          cd build/test/
          ctest --build-config Release
