name: Library

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - uses: actions/cache@3
        with:
          path: ~/.cache/ccache
          key: ${{ runner.os }}-library
      
      - name: install required packages
        run: |
          sudo apt-get update && sudo apt-get install -y cppcheck ccache

      - name: configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug

      - name: build test app
        run: cmake --build build --target pawndb_tests -j4

      - name: run test app
        run: |
          cd build/test/
          ctest --build-config Debug
