name: Standalone

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - uses: actions/cache@3
        with:
          path: ~/.cache/ccache
          key: ${{ runner.os }}-standalone
      
      - name: install required packages
        run: |
          sudo apt-get update && sudo apt-get install -y cppcheck ccache 

      - name: configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug

      - name: build app
        run: cmake --build build --target pawndb_app -j4

      - name: run app
        run: ./build/standalone/pawndb_app
