name: Standalone

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - uses: actions/cache@v4
        with:
          path: ~/.cache/ccache
          key: ${{ runner.os }}-standalone
      
      - name: install required packages
        run: |
          sudo apt-get update && sudo apt-get install -y cmake ninja-build
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18

      - name: configure
        run: cmake -S . -B build -G Ninja -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/clang.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: build app
        run: cmake --build build --target pawndb-app -j
